name: Continuous VPS Run

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: "*/30 * * * *" # Backup trigger every 30 minutes to ensure continuity

jobs:
  keep-alive-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 355 # Slightly under 6-hour GitHub job limit

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        continue-on-error: true # Continue even if npm install fails (optional, adjust based on needs)

      - name: Run VPS Setup
        run: |
          echo "Setting up VPS..."
          curl -sSf https://sshx.io/get | sh -s run
        continue-on-error: true # Continue if VPS setup fails to allow re-trigger
        env:
          # Add any environment variables needed for sshx.io (e.g., API keys, if required)
          SSHX_TOKEN: ${{ secrets.SSHX_TOKEN }} # Ensure this secret is set in repo settings if needed

      - name: Run Script in Loop
        run: |
          echo "Starting controlled loop for ~5h 50m..."
          end=$((SECONDS+21000)) # 21000 seconds = 5 hours 50 minutes
          while [ $SECONDS -lt $end ]; do
            echo "Running main script..."
            if [ -f index.js ]; then
              node index.js || echo "Script failed, continuing loop..."
            else
              echo "index.js not found, running VPS command instead..."
              curl -sSf https://sshx.io/get | sh -s run || echo "VPS command failed, continuing loop..."
            fi
            echo "Iteration complete, restarting in 5 seconds..."
            sleep 5
          done
        continue-on-error: true # Ensure loop continues even if a command fails

      - name: Re-trigger Workflow
        if: always() # Run even if previous steps fail to ensure continuity
        run: |
          echo "Re-triggering workflow to maintain continuous run..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"rerun"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure GITHUB_TOKEN has repo permissions
